spring:
  -profiles:
    active: "prod"
    default: "dev"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration