spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration